import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { fetchposts } from '../store/action/postAction'
import styles from '../styles/Home.module.css'

export default function Home() {
  // const [state, setState] = useState([])
  // const [items, setItems] = useState([])
  const dispatch =useDispatch();
  const {posts}= useSelector(state=>state.post)
  // const [loading,error,post] =posts

  useEffect(()=>{
    dispatch(fetchposts())
  //  console.log(posts,'heyyyy');
  //  setItems(posts)

  },[dispatch])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* {items && posts.map(item=>(
          <h1 >{item.title}</h1>
        ))} */}

        <h1>{posts.title}</h1>
        <p>{posts.price}</p>
        <p>{posts.description}</p>
        <img src={posts.image} alt="" />


        
      </main>
{/* 
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
